<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\BaseController;
use App\Http\Requests\MakeIsCalledRequest;
use App\Http\Requests\SaveCityRequest;
use App\Http\Requests\SavePostRequest;
use App\Models\Blog\Category;
use App\Models\Blog\Post;
use App\Models\CallRequests;
use App\Models\City;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CallRequestsController extends BaseController
{

    public function __construct()
    {
        $this->viewData = [
            'form'  => 'manager.pages.callRequests.form',
            'list'  => 'manager.pages.callRequests.list'
        ];

        parent::__construct();
    }

    public function list(Request $request, ?array $ordering = ['created_at', 'DESC'])
    {

        $this->model = $this->model
            ->orderBy('is_called','ASC')
            ->orderBy('id','DESC');
        return parent::list($request, $ordering); // TODO: Change the autogenerated stub
    }

    public function isCalled(MakeIsCalledRequest $request)
    {
        $callRequest = CallRequests::findOrFail($request->call_request_id);

        $callRequest->is_called = true;
        $callRequest->save();

        $this->redirect = route('manager.call-requests.list');

        return $this->responseJson(true, __('informationSaved'));
    }

    function makeModel(): string
    {
        return CallRequests::class;
    }
}
