<?php
namespace App\Http\Controllers\Manager;

use App\Http\Controllers\BaseController;
use App\Http\Requests\SaveBlogCategoryRequest;
use App\Http\Requests\SavePayablePacket;
use App\Models\PayablePacket;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PayablePacketController extends BaseController
{

    public function __construct()
    {
        $this->viewData = [
            'form'  => 'manager.pages.payable-packets.form',
            'list'  => 'manager.pages.payable-packets.list'
        ];

        parent::__construct();
    }

    public function list(Request $request, ?array $ordering = ['created_at', 'DESC'])
    {

        return parent::list($request, $ordering); // TODO: Change the autogenerated stub
    }


    public function store(SavePayablePacket $request)
    {
        $data = $request->except('_token','id');

        if ($request->isActive == "on"){
            $data['is_active'] = true;
        }

        if ($request->redirect) {
            $this->redirect = $request->redirect;
        }

        if ($request->id){
            $category = PayablePacket::updateOrCreate(['id'=>$request->id], $data );
        }else{
            $category = PayablePacket::create($data );
        }

        if ($request->media){
            $category->images()->detach();
            $category->images()->attach((int) $request->media , [ 'other_entity'=>  PayablePacket::class ]);
        }

        return $this->responseJson(true, __('informationSaved'));
    }

    function makeModel(): string
    {
        return PayablePacket::class;
    }
}

